### ISSUE TITLE
Can't compile in C (C++ works)

### ISSUE THREAD

**Issue by aleksazr** [makuke1234/PongD2D#5]
Hello,

can you tell me which SDK version are you using, where did you get it...

I'm using Visual Studio Community 2022 and can't compile dwrite.h in C mode.

An example line from dwrite.h
```
interface DWRITE_DECLARE_INTERFACE("739d886a-cef5-47dc-8769-1a8b41bebbb0") IDWriteFontFile : public IUnknown
```

preprocessed to C++
```
struct __declspec(uuid("739d886a-cef5-47dc-8769-1a8b41bebbb0")) __declspec(novtable) IDWriteFontFile : public IUnknown
```

preprocessed to C
```
struct   IDWriteFontFile : public IUnknown
```
and the part " : public IUnknown" gets in the way.

I have zero experience with C++, but it looks to me as this is a Microsoft bug, they simply forgot about C.
But then, how do you compile it?

**Comment by makuke1234** [comment]
I agreee on the point being simply a Microsoft bug. As you may see from my makefile I am using GNU C Compiler & GNU C++ Compiler for the wrapper. I am using the MSYS2 platform https://www.msys2.org/ that allows me to build native Windows applications with MinGW port of GCC & G++.

**Comment by aleksazr** [comment]
Thank you. Maybe you should add that info to the readme.

**Comment by makuke1234** [comment]
Thank you for requesting additional information! All included in the readme now.
