### ISSUE TITLE
BUG report

### ISSUE THREAD

**Issue by aleksazr** [makuke1234/PongD2D#6]
Start a game, so that the ball is actually moving, and press alt F4.

You might execute d2dwrapper.cpp dxFactoryCreateRectangleGeometry, called from a thread in logic.c,
at the time logic->pong->dx.factory is already cleared.

On WM_CLOSE, you don't first shut down the thread.

**Comment by makuke1234** [comment]
Thank you for input, the bug is being fixed!

**Comment by makuke1234** [comment]
Now fixed. See release 1.3.3
